modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "vrjester"
version = "${version}"
displayName = "VR Jester API"
authors = "Caliburs"
description = '''
A Minecraft mod API to allow developers to implement gesture controls in VR for their mod.'''
logoFile = "icon.png"

[[dependencies.vrjester]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrjester]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrjester]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.8,)"
ordering = "AFTER"
side = "BOTH"