modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "vrjester"
version = "${version}"
displayName = "VR Jester API"
authors = "Caliburs"
description = '''
A Minecraft mod API to allow developers to implement gesture controls in VR for their mod.
'''
logoFile = "icon.png"

[[dependencies.vrjester]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrjester]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrjester]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.93,)"
ordering = "AFTER"
side = "BOTH"